name: Notify Endpoints Generator

on:
  workflow_run:
    workflows: ["Publish Package to npmjs"]
    types:
      - completed
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Send Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: keshavsoft/vs-code-ext-express-api-gen-endpoints
          event-type: kschema_published
